server:
  servlet.context-path: /covidbot/api
  port: 8080
app:
  job:
    covid-real-time-data:
      enabled: true
      cron-expression: "0 0/10 * * * *"
      config:
        url: "https://api.covid19api.com/summary"
  twilio:
    sid: ${twilio.sid}
    auth-token: ${twilio.auth.token}
